server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:   #Configuration for creating User service as a client
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true #this property is by default true just added for learning purpose
    register-with-eureka: true #this property is by default true just added for learning purpose
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker: # Configuration for circuit breaker
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

#Circuit Breaker How it works:
  #
  #The circuit breaker starts in the closed state (requests are allowed).
  #If failures accumulate (e.g., requests consistently fail), the circuit breaker switches to the open state, rejecting requests immediately.
  #After a predefined time, the circuit breaker enters a half-open state and allows a limited number of requests to pass through to see if the service has recovered. If the service is still failing, it goes back to the open state.
  #Once the service recovers, the circuit breaker goes back to the closed state.

  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3                # The number of retry attempts before failing
        wait-duration: 5s              # Delay between retries (5 seconds)
        interval-function: "exponentialBackoff(500ms, 1.5)"
        retry-on-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException

  rateLimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2 #maximum number of requests here it is 2
        wait-duration: 0s

#The rate limiter allows 2 requests every 4 seconds.
#Once the rate limit (2 requests) is reached, any subsequent requests will not be processed immediately and will be rejected without waiting (because wait-duration is 0s).
#The rate limit will reset after 4 seconds.

