server:
  port: 8082

spring:
  application:
    name: Rating-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:   #Configuration for creating Rating service as a client
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true # this property is by default true just added for learning purpose
    register-with-eureka: true # this property is by default true just added for learning purpose
    service-url:
      defaultZone: http://localhost:8761/eureka